name: ilajak
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Routing
  go_router: ^14.8.1

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.1.4

  # Dependency Injection
  get_it: ^8.0.3

  # Functional Programming
  fpdart: ^1.1.1

  # Localization
  easy_localization: ^3.0.7

  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4

  # UI / Responsive
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  skeletonizer: ^1.4.3
  hugeicons: ^0.0.8

  # Images
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # Utilities
  logger: ^2.5.0
  intl: ^0.20.2
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
